config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  resources :artists do
      resources :songs, :only => [:create, :new, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true
  validates :country, presence: false
  validates :image, presence: false
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
  validates :duration, presence: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def destroy
      @artist = Artist.find(params[:id])
      @artist.destroy
      redirect_to @artist
    end

  private
  def artist_params
    params.require(:artist).permit(:name, :country, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.artist = Artist.find(params[:artist_id])
    if @song.save
      redirect_to @song.artist
    else
      render 'new'
    end
  end

  def destroy
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.find(params[:id])
    @song.destroy
    redirect_to @artist
  end

  private
  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :duration, :artist_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/index.html.erb
<h2>Welcome to Codaisseurify! :)</h2>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2>Artists </h2>
  </div>
  <div class="panel-body">
    <div class="row">
        <% @artists.each do |artist| %>
          <div class="col-sm-4">
            <div class="col-sm-12">
              <%= image_tag artist.image, class: "small-image-size" if artist.image.present? %>
            </div>
            <div class="col-sm-12">
              <%= link_to artist.name, artist_path(artist.id) %>
            </div>
            <div class="col-sm-12">
              <label>Number of songs: <%= artist.songs.length %></label>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class="panel panel-primary">
   <div class="panel-heading"> <h2><%= @artist.name %></div></h2>
    <div class="panel-body">
      <p>Country: <%= @artist.country %></p>

      <% if @artist.image? %>
        <%= image_tag @artist.image, class: "small-image-size" %>
      <% end %>

      <h4>List of songs:</h4>

      <% if @artist.songs.any? %>
        <ul>
          <% @artist.songs.each do |song| %>
            <li>
              <p><%= song.title %></p>
              <p>Duration: <%= song.duration %></p>
            </li>

            <%= link_to 'Delete song', artist_song_path(@artist, song), method: :delete, data: { confirm: 'Are you sure that you want delete this song?'}, class: "btn btn-default"  %>

            <br><br>
          <% end %>
          </ul>
      <% else %>
        <p>There are no songs from this artist.</p>
      <% end %>
<%= link_to 'Add Song', new_artist_song_path(@artist), class: "btn btn-default" %>
  </div>
</div>
<%= link_to "Delete Artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
<%= link_to "Back to Artists", root_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/profiles/edit.hmtl.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        
      </ul>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for [@song], :url => artist_songs_path do |f| %>
<div class="panel panel-primary">
   <div class="panel-heading">
     <h2><%= Artist %></div></h2>
    <div class="panel-body">

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, id: :title, class:"form-control" %>
      </div>

      <div class="from-group">
        <%= f.label :duration %>
        <%= f.text_field :duration, id: :song_duration, class:"form-control" %>
      </div>

<br>
      <div class="actions">
        <%= f.submit (@song.new_record? ? "Create" : "Update"), class: "btn btn-primary" %>
      </div>
    </div>
</div>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<%= render 'form' %>
<br>
<%= link_to 'Back to artists', artists_path, class: "btn btn-default" %>